kind: pipeline
type: exec
name: package

platform:
  os: darwin
  arch: amd64

clone:
  disable: true

steps:
  - name: macOS
    commands:
      - echo build macOS Install dmg
      - cd /Users/tqcenglish/SrcCode/Work/Broadcast/search-device-tool
      - pwd
      - make all
    when:                                
      branch:
      - master

trigger:
  branch:
  - master
  event:
  - push